version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: sat-vis-minio
    ports:
      - "9000:9000"  # API Port (Go talks to this)
      - "9001:9001"  # Console Port (You use this in Browser)
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  # (Optional) We can add your Go and Python services here later